# Настройки DOSBox-X для игры Billy
[sdl]
fullscreen      = true
fullresolution  = desktop
windowresolution= 1200x900
output          = opengl
autolock        = true
showmenu        = false

[dosbox]
title           = Billy
machine         = svga_s3
memsize         = 32
fastbioslogo    = true
startbanner     = false
quit warning    = false

[render]
aspect          = true
scaler          = none
glshader        = sharp

[cpu]
core            = auto
cputype         = pentium
cycles          = auto

[mixer]
rate            = 44100

[sblaster]
sbtype          = sb16
sbbase          = 220
irq             = 7
dma             = 1
hdma            = 5
oplmode         = auto

[autoexec]
@echo off
mount c game -q
c:
billy
exit
